apiVersion: v1
kind: Secret
metadata:
  name: ms-productos-secret
  namespace: ms-productos-namespace
type: Opaque
data:
  SERVER_PORT: ODA4MQ==             
  DB_HOST: aG9zdC5kb2NrZXIuaW50ZXJuYWw=     
  DB_PORT: NTQzMg==                           
  DB_NAME: cG9zdGdyZXM=                      
  DB_USER: cG9zdGdyZXM=                 
  DB_PASSWORD: cGFzc3dvcmQ=               
  DB_SSL_MODE: ZGlzYWJsZQ==           