server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-productos
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?sslMode=${DB_SSL_MODE:disable}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}