apiVersion: v1
kind: Secret
metadata:
  name: ms-pedidos-secret
  namespace: ms-pedidos-namespace
type: Opaque
data:
  SERVER_PORT: ODA4Mg==                      
  DB_HOST: aG9zdC5kb2NrZXIuaW50ZXJuYWw=      
  DB_PORT: NTQzMg==                             
  DB_NAME: cG9zdGdyZXM=                         
  DB_USER: cG9zdGdyZXM=                        
  DB_PASSWORD: cGFzc3dvcmQ=                   
  DB_SSL_MODE: ZGlzYWJsZQ==              
  PRODUCTOS_SERVICE_URL: aHR0cDovL21zLXByb2R1Y3Rvcy1zZXJ2aWNlLm1zLXByb2R1Y3Rvcy1uYW1lc3BhY2Uuc3ZjLmNsdXN0ZXIubG9jYWw6ODA4MQ==